version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bibliotech_app
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www/html
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - DB_CONNECTION=pgsql
      - DB_HOST=database
      - DB_PORT=5432
      - DB_DATABASE=bibliotech
      - DB_USERNAME=postgres
      - DB_PASSWORD=secret
    depends_on:
      - database
    command: php artisan serve --host=0.0.0.0 --port=8000
    networks:
      - bibliotech_network

  database:
    image: postgres:15-alpine
    container_name: bibliotech_db
    environment:
      POSTGRES_DB: bibliotech
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_INITDB_ARGS: "--encoding=UTF8"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - bibliotech_network

volumes:
  postgres_data:
    driver: local

networks:
  bibliotech_network:
    driver: bridge
