# Docker Compose pour GitHub Codespace
# Configuration optimisée pour développement cloud

version: '3.8'

services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/workspace:cached
    environment:
      - APP_ENV=development
      - APP_DEBUG=true
      - DB_HOST=database
      - DB_DATABASE=bibliotech
      - DB_USERNAME=postgres
      - DB_PASSWORD=secret
      - MAIL_HOST=mailhog
      - MAIL_PORT=1025
    depends_on:
      - database
      - mailhog
    networks:
      - codespace
    command: sleep infinity
    user: vscode

  database:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=bibliotech
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - codespace
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  mailhog:
    image: mailhog/mailhog
    networks:
      - codespace

volumes:
  postgres_data:

networks:
  codespace:
    driver: bridge
